### PR TITLE
#77 Migrate to Google games services v2

### PR DESCRIPTION
**Pull request by Abedalkareem**
#77 Migrate to Google Games Services v2.

I tested this with my game client and it worked fine, however, I need more people to test it before merging it!

Please feel free to test using this branch:
feature/update_to_games_services_v2

In your pubspec.yaml
```
  games_services:
    git: 
      url: https://github.com/Abedalkareem/games_services.git
      path: games_services
      ref: feature/update_to_games_services_v2
```

### CODE REVIEW

**Comment by egonbeermat** [comment]
I'll give this a whirl in the next day or so, and report back. Thanks!

**Review by egonbeermat — APPROVED** [review]
Have tested these changes in my app in Android emulators API levels 30 & 31, and on a physical device API level 33. I do not use saved game, so I don't request the additional scope SCOPE_APPFOLDER. Achievements setting and retrieval worked as expected, as did submitting and retrieving Leaderboard scores. Sign-in worked silently and also, after using Play Games to sign my account out of all apps, was presented with the sign-in dialog on app startup.

**Comment by theLee3** [comment]
I will give this a try tonight or tomorrow and report back.

**Comment by theLee3** [comment]
Tested in debug & release on emulator & physical device (both API 33).

⚠️ `signIn` works with saved game enabled & disabled **BUT** when disabled, the method never returns. Therefore, awaiting it (i.e. during a loading screen) just hangs. Is this a limitation of v2 or something that we can address?

✅ `getPlayerID`, `getPlayerName`, `getPlayerIconImage`, `getPlayerHiResImage`
✅ `showLeaderboards` & `showAchievements`
✅ `loadLeaderboardScores` & `loadAchievements`
✅ `submitScore` & `unlock`
✅ `saveGame`, `loadGame`, `deleteGame` & `getSavedGames`

❌ `isSignedIn` - always `false` when signed in via v2 (saved game disabled)

**Comment by Abedalkareem** [comment]
@theLee3 
Nice catch 🚀, I fixed that issue.

**Comment by theLee3** [comment]
Awesome! Everything seems to work. Great job!!

**Comment by egonbeermat** [comment]
Based on user reports and further testing in the Android emulator, I am seeing the same as above - **isSignedIn** often returns **false** even when actually signed in via v2 with saved game disabled. Is this expected behavior?

I have code that prevents interactions with Play Games if this is false, to theoretically avoid errors. However, if I ignore isSignedIn returning false and try to load achievements, submit scores, get player name, etc, these all work fine without error - I am signed in, even though isSignedIn returns false.

Some guidance on the use/validity of **isSignedIn** would be appreciated.

**Comment by theLee3** [comment]
I believe you are correct about this. This is the approach I am looking into as well. I have only taken a precursory glance at the v2 migration docs, but they mention using GoogleSignIn in **conjunction** with GamesSignIn. I am curious if we pass the authenticated player to PlayGames somehow, allowing us to use the modern methods throughout for both auth variations. I will dig into it tonight.

**Comment by egonbeermat** [comment]
@theLee3 Look forward to hearing your thoughts. I modified my sign-in with `shouldEnableSavedGame: true` to force  the use of `googleSignInClient`, but left the `isSignedIn` using the `gamesSignInClient` and, as expected, this didn't return the correct sign-in status, so it appears a new solution is required in the current code base to return accurate results, depending on the sign-in method.

**Comment by theLee3** [comment]
@egonbeermat So there is no interop between GoogleSignIn and PlayGamesSignIn. It seems to me that the best (only?) approach is to attempt `GoogleSignIn.getLastSignedInAccount`. If null is returned, meaning GoogleSignIn was not used, follow up with `GamesSignInClient.isAuthenticated`.
The following was successful for me:
```
fun isSignedIn(activity: Activity?, result: MethodChannel.Result) {
    activity ?: return
    val account = activity!!.let { GoogleSignIn.getLastSignedInAccount(it) }
    if (account != null) {
      result.success(true)
      return
    }
    
    val gamesSignInClient = PlayGames.getGamesSignInClient(activity)
    gamesSignInClient.isAuthenticated.addOnCompleteListener { isAuthenticatedTask: Task<AuthenticationResult> ->
    val isAuthenticated = isAuthenticatedTask.isSuccessful &&   isAuthenticatedTask.result.isAuthenticated
    result.success(isAuthenticated)
}
```

Please let me know your results with this approach.

**Comment by theLee3** [comment]
What differences are you experiencing on iOS? Is it after a single cancellations, or multiple refused sign-in attempts?

**Comment by theLee3** [comment]
Google really did a number on us moving to v2 while leaving GameSave permissions separate, requiring 2 separate logins. Here is what I have deduced...

First, let's talk about the v2 flow sign-in flow:
1) The game automatically signs in (or attempts to) when the app is launched. This means that there is no need for an explicit call to `signIn` (silent or explicit) on launch. All we need to do is check the result of `isSignedIn, using v2's isAuthenticated.
2) If the user refuses sign in, we can provide a sign in method that will only invoke the v2 sign-in flow.
3) We can also provide a sign out button.

Now, how does this differ when dealing with SaveGames..? Well, all of this should still be used as is. The difference is that we must **additionally** request the SavedGame scope using GoogleSignIn. Note that the docs state "_...we recommend you use the Google Sign In SDK **alongside** Play Games Service_". The scope permissions are then passed along to the PlayGames method calls for SavedGame access.

Therefore, I propose the following:
1) Reduce the `signIn` method to only call the v2 sign-in flow.
2) `isSignedIn` returns the result of `gamesSignInClient.isAuthenticated`.
3) A new `enableSavedGames` method calls the GoogleSignIn flow with scope.
4) A new `savedGamesEnabled` getter returns the result of `isSignedIn` & `GoogleSignIn.getLastSignedInAccount`.

What are your thoughts on this?

I am in the process of testing this implementation now, as well as updating doc comments. I will post a link once uploaded.

**Comment by theLee3** [comment]
As for the iOS oddity, the isSignedIn status comes straight from the `isAuthenticated` getter provided by the GKLocalPlayer object, and I believe it misbehaves sometimes when sandbox testing on Simulator. I suggest turning Game Center off on Simulator when testing features while not signed in, or perhaps adding a `kDebugMode && playerId != null` check to act as a signIn check during debug. I am not sure if the `playerId` getter is affected the same way as the `isAuthenticated` getter.

**Comment by egonbeermat** [comment]
Google have done a number on us on a few APIs :) Part and parcel of the growth and evolution over time, though, so I am tolerent, although I do feel Apple generally do a better job of evolving and documenting their APIs (said begrudgingly as a lifetime Android user).

On the surface, your proposed flow for Android looks good, not just to work around the sign-in issue, but that it offers a least-privilege path for developers to utilize all of Play Games in their app except their save game option. Giving the option for the user to toggle the save games explicitly gives more context to the OAuth window presented too, imho. As proposed, the developer can also utilize the same app logic flow on each platform if `enableSavedGames` and `savedGamesEnabled` are stubbed on iOS, without need for divergent `if (Platform.isAndroid)`, etc., so I think your approach is sound, especially if the documentation reflects this behavioral difference!

As for the sandbox testing, I prefer the ease and speed of development utilizing the iOS Simulator / Android emulator, but having just about concluded adding in_app_purchases, which requires a physical iOS device for testing, I think my time using the iOS Simulator for development is just about over, given the other issues with it too.

**Comment by theLee3** [comment]
Touché and agreed.

Give this a try.

```
games_services:
    git: 
      url: https://github.com/theLee3/games_services.git
      ref: separate-sign-in-and-enable-saved-game
      path: games_services
```

Play Games v2 doesn't have an implementable sign out functionality, as it is handled at the OS level now (like iOS). Therefore we can probably do away with the `signOut` method as it would really serve no purpose with how we are implementing saved game functionality.

I also think we should remove the email scope from the `GoogleSignIn` request as it is IMHO outside of the intended scope of the plugin. Any additional scopes outside of the immediate use of `PlayGamesServices` should likely be handled by the `google_sign_in` plugin.

**Comment by theLee3** [comment]
After further testing, I don't think we have to request an additional scope for saved games anymore!! 🤯 but also 😅

I think we can all agree that the documentation regarding this matter is very poor. I am removing all GoogleSignIn and saved game enablement functionality. updating the repo listed above. Please let me know if there is any issue.

**Comment by theLee3** [comment]
Repo has been updated.

**Comment by egonbeermat** [comment]
I was just going to say, I had seen a [ StackOverflow comment ](https://stackoverflow.com/questions/71527045/how-to-implement-saved-games-on-google-play-games-services-v2-sdk)that had mentioned it was no longer necessary, but I never really followed up researching that. I think I was convinced you needed to request additional scopes with v2, but it seems the line in the v2 documentation that states 'With Play Games Services V2 you cannot request any additional scopes' and guides you to the Google Sign-in documentation, along with the knowledge that you had to do this in V1, leads to an assumption that the need still persists, as it's not explicitly called out otherwise. But still, good news!

I'll check out the repo shortly - I have some local modifications for extra functionality in games_services, so I can't just switch out the package reference.

**Comment by theLee3** [comment]
Once I discovered this to be the case, I launched a Google search on the subject and that post is the only information I came across as well.

Understood.

**Comment by egonbeermat** [comment]
Quick and dirty - incorporated the changes, works in brief tests where app previously logged in and also app logging in / cancel logging in, after forced sign out from Play Games. Works as expected!

Minor: `games_services_platform_interface/lib/game_services_platform_interface.dart` still has comment at line 105-106 about `shouldEnableSavedGame`

Does the version deserve a bigger bump than 3.1.0, with breaking changes and PlayGames v2 and an simpler implementation interface? :)

will look more tomorrow!

**Comment by theLee3** [comment]
Great! I will remove that comment shortly.

I was wondering the same. Definitely, have to get it out of 3.0.x. Not sure if the convention for breaking changes would push us to 4.0.0. I just started looking into it when you posted.

**Comment by egonbeermat** [comment]
Have tested this more on debug-signed build on device and simulator, and have released this as a release-signed build on Open Testing track and tested, and all seems well.

**Comment by theLee3** [comment]
Pull request submitted.
Thanks a lot for your help and feedback @egonbeermat.

**Comment by egonbeermat** [comment]
Excellent! Thanks for attacking this problem! It ended up in a much better place!

**Comment by Abedalkareem** [comment]
Amazing guys! I'll check the PRs 🚀.  
It's really annoying that the documentation mentions that requesting scope is required 😅.

Can we do one test before going forward? can you try with an account you never logged in with your game before?
Maybe because you gave access to the drive before it's getting success? Just to confirm?

**Comment by theLee3** [comment]
Yeah, GPG v2 is an awesome upgrade marred by a less than clear upgrade guide. Glad we all were able to figure it out... eventually 😅

I just tried it with an account that had never been used and was able to access the cloud saves feature.

I also noticed that cloud saves are explicitly listed as a feature in the v2 sign in prompt (as seen below). I believe this is a different presentation from the v1 prompt where you had to request the Drive scope.

GPG Login Prompt

**Comment by egonbeermat** [comment]
This was a bit of a rabbit hole :) I wiped an API level 31 emulator clean, and created a new account. At account creation, it asked for a phone number to send a verification code, so I entered my phone number, and it duly sent a code and allowed the account creation. At the first Google sign-on attempt though (via Play Store), it requested a phone number due to 'suspicious activity' and when I re-entered the same phone number, it refused, saying it had been used too many times. 

Not having another phone number and not seeing any alternative ways to validate, I gave up, launched my app and in the Play Games sign-in prompt, I used my previous testing account, and selected 'Continue as....'. At this point, I am presented with another popup to "Install Google Play Games" (presumably because I wiped the emulator):
 
Screenshot_1696858493

If I choose 'Not now', it dismisses - and `isSignedIn` is `false`. I also see the auth.kt signIn log:
`I/PlayService(15886): isAuthenticated: false toString: com.google.android.gms.games.AuthenticationResult@3fa83c7`

This popup contradicts what the [V2 guide](https://developers.google.com/games/services/android/signin) states:

> The Play Games Services v2 SDK brings a number of improvements that increase the number of users signed into your game, and make development easier:
> 
> Improvements for users:
> After selecting a default account, users are logged-in without needing to interact with a prompt.
> **Users no longer need to download the Play Games App to sign-in with Play Games Services** or create a new account

This could be an emulator quirk, a first-time quirk, a legacy-account quirk.....will investigate!

**Comment by egonbeermat** [comment]
I wasn't aware it was for API level >31, so that would be it. I started with a clean API 33 emulator, and auth, submitting scores, loading achievements and loading scores / querying a scores rank all inside the game via API calls worked. Only when I try to launch the Play Games presentation of Achievements or Leaderboards, I received this prompt:

Screenshot_1696890575

Which makes sense to me, so I'm good!

One final note for this version - is it worth going for the latest and greatest versions of games-v2 and auth? I have tested with both games-v2:17.0.0 and 19.0.0, and auth:20.6.0 and 20.7.0 without apparent issue.

```
dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8:$kotlin_version"
    implementation 'com.google.code.gson:gson:2.10.1'
    api "com.google.android.gms:play-services-games-v2:19.0.0"
    api 'com.google.android.gms:play-services-auth:20.7.0'
}
```

**Comment by theLee3** [comment]
Just to clarify, I wasn't sure that it requires API level >31, and I didn't manage to verify this anywhere. It seems documentation is lacking again. However, given your experience, it certainly makes sense.

And good call, we definitely should use that latest that we can.

**Comment by theLee3** [comment]
@egonbeermat I just discovered this and thought back to you and this thread, so I'm gonna leave this here.

We can now test in-app purchases via Simulator using an [Xcode StoreKit configuration](https://developer.apple.com/documentation/storekit/in-app_purchase/original_api_for_in-app_purchase/testing_in-app_purchases_in_xcode).

**Comment by egonbeermat** [comment]
@theLee3 Hey there! Yes, I had discovered that too, and it's somewhat useful for initial testing on an emulator. However, I also validate receipts off-device, and it doesn't support that. For once, Google has Apple beat on this, allowing full end-to-end testing without compromise :)

**Comment by theLee3** [comment]
Yeah, I am in the same boat.
Haha! +1 for Google this time.

**Pull request merged**
