### PR TITLE
Add TTG game in Apps section in the README.md

### PR DESCRIPTION
**Pull request by imaNNeo**
Hi. I just added my game to the README.md

TTG - Through The Galaxies 🚀 casual game

<image src="https://user-images.githubusercontent.com/7009300/214796349-3fa3135c-0f57-4223-8830-454910a5d880.png" width=300 />

### CODE REVIEW

**Comment by Abedalkareem** [comment]
Amazing game, I tried it and it's fun to play!

I think you have an issue with implementing the plugin I'm tapping on the cup icon but nothing is happening.

Did you add the Google play console SHA1? 

In the google play console, go to your app then Release -> Setup -> App integrity -> App Signing -> SHA-1 certificate fingerprint

Get that SHA1 and add it to your Play Games Services Configuration

 
Screenshot 2023-02-14 at 9 49 10 AM
Screenshot 2023-02-14 at 9 48 48 AM

**Comment by imaNNeo** [comment]
> Amazing game, I tried it and it's fun to play!
> ...

Hi, There is a bug in the 1.2.5 version. 
It will be fixed in the next version. I will let you know here when I release a new version.

**Comment by imaNNeo** [comment]
It should be fixed in our latest version 1.3.0
Can you please check it out again?

**Review by Abedalkareem — APPROVED** [review]
Amazing game!

**Pull request merged**
