### PR TITLE
Exclude Gson serialized data models from obfuscation.

### LINKED ISSUE #90: Achievements.loadAchievements weird
`Achievements.loadAchievements()` not works when in `release` build, but works in `debug` build.

Other methods `GamesServices.signIn()`, `GamesServices.getPlayerName()`, `GamesServices.getPlayerScore(...)` work for both.
So no idea what's going on.

I think it's for any Android, but I tested on Android 12, flutter:3.3.3

### PR DESCRIPTION
**Pull request by theLee3**
Fixes #90.

### CODE REVIEW

**Review by Abedalkareem — APPROVED** [review]
Nice!
Thank you for your contribution, you are one of the guys who are making this plugin continue to work and get more users!

**Comment by theLee3** [comment]
Thank you for the acknowledgment. And congrats on the plugin being included in Flutter's Casual Games Toolkit list! Great work on the plugin from day 1.
Actually, my first commit to this repo was my first commit ever to an open source project! So thanks for that opportunity as well.

**Comment by egonbeermat** [comment]
Are the correct class names included in that? I'm not deeply familiar with Gradle/Kotlin/Pro-Guard/plug-in development so I could be wrong, but in the commit it has:

-keep class com.abedalkareem.games_services.models.LeaderboardScores { <fields>; }

but 'LeaderBoardScores' neither matches the file name in the models dir (LeaderBoardScoreData.kt) or the class name in that file (LeaderboardScoreData). Same is true for: 

-keep class com.abedalkareem.games_services.models.SaveGame { <fields>; }

but file (and class) names in models dir are SavedGame

AchievementItemData matchs in the pro-guard rule to the class name in models.

Help me understand :) My achievements are working in release mode on Android, and leaderboard scores are not. They all work in debug mode....

**Comment by theLee3** [comment]
You are correct about the class names. They should match. I will submit a pull request today. In the meantime, you can create an app level `proguard-rules.pro` file with the correct class names and it will resolve your issue. Please confirm if that works for you.

**Comment by egonbeermat** [comment]
Thanks! I actually cloned the repo and modified the `proguard-rules.pro` locally, then created a release build and pushed it through Play Console to get it signed appropriately, and it seems to work now!

**Comment by theLee3** [comment]
Great! The fix has been merged now as well.

**Pull request merged**
