### PR TITLE
macOS Support

### PR DESCRIPTION
**Pull request by jonafeucht**
PR adds support for macOS.

### CODE REVIEW

**Comment by Abedalkareem** [comment]
Amazing! Thank you for creating the pull request, I can see there are a lot of changes not related to the macOS support, like the android part and the license. Can you please remove these changes?

**Comment by jonafeucht** [comment]
> Amazing! Thank you for creating the pull request, I can see there are a lot of changes not related to the macOS support, like the android part and the license. Can you please remove these changes?

Alright, thanks for pointing that out. Somehow missed reverting those changes after testing.

**Comment by EliaTolin** [comment]
please merge.
It is very useful.

**Review by Abedalkareem — APPROVED** [review]

**Comment by Abedalkareem** [comment]
Thank you for adding this!

**Pull request merged**
