### PR TITLE
Add silentSignIn and setSteps

### PR DESCRIPTION
**Pull request by qinzhe**
1. Add silentSignIn method.
2. Add setSteps method for Android achievements.

### CODE REVIEW

**Comment by EliaTolin** [comment]
This fix the login prioblem?

**Comment by Abedalkareem** [comment]
Hi,
We are already calling silent signing if you check `silentSignIn` method in the android plugin you will see that we are doing that there, now if that fail then we are calling `explicitSignIn`.

**Comment by qinzhe** [comment]
I want explicitSignIn not to be called automatically when silentSignIn fails.

**Comment by Abedalkareem** [comment]
Hi @qinzhe !
In that way, we will not be able to use any of the leaderboards or achievements features as login is a prerequisite to use these features.

Can you please explain the use case for this?

Thanks,

**Pull request closed without merging**
