### PR TITLE
Clean up doc comments to be more clear and concise.

### PR DESCRIPTION
**Pull request by theLee3**
Just a little tweaking of the doc comments to fix typos and make more clear and concise where possible.
Also moved `isAuthenticated` from `BaseGamesServices` to `Auth` for better clarity.

No functionality is changed whatsoever.

### CODE REVIEW

**Review by Abedalkareem — APPROVED** [review]
Amazing!

**Review by Abedalkareem — APPROVED** [review]

**Comment by Abedalkareem** [comment]
@theLee3  There is a minor conflict here

**Comment by theLee3** [comment]
Ah yes. I submitted for the pre-4.0.0 build. I will rebase from the current develop branch.

**Comment by theLee3** [comment]
Updated for version 4.0.0. Should be good now.

**Pull request merged**
