### PR TITLE
Add increment method for Android achievements

### PR DESCRIPTION
**Pull request by tommybuonomo**
Hey @Abedalkareem ,
The increment method was not available for Android achievements. 
I added it to the project.
Tested and OK on a real app.

Thanks 💯

### CODE REVIEW

**Comment by tommybuonomo** [comment]
@Abedalkareem, 
Please consider again this PR to add the `increment` method (more information about the method [here](https://developers.google.com/games/services/common/concepts/achievements#incremental_achievements))

I'm using it for two games on the PlayStore: [Nonogram Colors](https://play.google.com/store/apps/details?id=com.tbuonomo.nonogramcolordot) and [Ripple Effect Puzzle](https://play.google.com/store/apps/details?id=com.tbuonomo.rippleeffectpuzzle)

Thanks :)

**Comment by Abedalkareem** [comment]
Hi!,

Sorry for the late reply I'll check it now.

**Review by Abedalkareem — APPROVED** [review]

**Comment by Abedalkareem** [comment]
@tommybuonomo 
I published the increment method!, also I added your apps to the readme file, I hope you are ok with that?

Thank you!

**Comment by tommybuonomo** [comment]
Totally ok @Abedalkareem ;) 
Thanks !

**Pull request merged**
